% Photosynthesis / Carbon Metabolism Model
model = createModel;

% CALVIN CYCLE

model = addReaction(model, 'RBPCh', ...
    'metaboliteList', {'rb15bp[h]', 'co2[h]', '3pg[h]'}, ...
    'stoichCoeffList', [-1, -1, 2], 'reversible', false);

model = addReaction(model, 'GAPDH_nadp_hi', ...
    'metaboliteList', {'3pg[h]', 'dhap[h]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

model = addReaction(model, 'ALDh', ...
    'metaboliteList', {'dhap[h]', 'e4p[h]', 's17bp[h]'}, ...
    'stoichCoeffList', [-1, -1, 1], 'reversible', true);

model = addReaction(model, 'SBPase', ...
    'metaboliteList', {'s17bp[h]', 's7p[h]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

model = addReaction(model, 'FBAh', ...
    'metaboliteList', {'dhap[h]', 'dhap[h]', 'fdp_B[h]'}, ...
    'stoichCoeffList', [-1, -1, 1], 'reversible', true);

model = addReaction(model, 'BFBPh', ...
    'metaboliteList', {'fdp_B[h]', 'f6p_B[h]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

model = addReaction(model, 'TKT1h', ...
    'metaboliteList', {'dhap[h]', 's7p[h]', 'xu5p_D[h]', 'r5p[h]'}, ...
    'stoichCoeffList', [-1, -1, 1, 1], 'reversible', true);

model = addReaction(model, 'TKT2h', ...
    'metaboliteList', {'dhap[h]', 'f6p_B[h]', 'xu5p_D[h]', 'e4p[h]'}, ...
    'stoichCoeffList', [-1, -1, 1, 1], 'reversible', true);

model = addReaction(model, 'TAh', ...
    'metaboliteList', {'e4p[h]', 'f6p_B[h]', 'dhap[h]', 's7p[h]'}, ...
    'stoichCoeffList', [-1, -1, 1, 1], 'reversible', true);

model = addReaction(model, 'RPEh', ...
    'metaboliteList', {'xu5p_D[h]', 'ru5p_D[h]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

model = addReaction(model, 'RPIh', ...
    'metaboliteList', {'r5p[h]', 'ru5p_D[h]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

model = addReaction(model, 'PRUK', ...
    'metaboliteList', {'ru5p_D[h]', 'rb15bp[h]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);


% PHOTORESPIRATION

model = addReaction(model, 'RBCh', ...
    'metaboliteList', {'rb15bp[h]', '3pg[h]', '2pglyc[h]'}, ...
    'stoichCoeffList', [-1, 1, 1], 'reversible', false);

model = addReaction(model, 'PGP', ...
    'metaboliteList', {'2pglyc[h]', 'glyclt[h]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

model = addReaction(model, 'GCLDH', ...
    'metaboliteList', {'glyclt[h]', 'glx[h]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

model = addReaction(model, 'T_glx', ...
    'metaboliteList', {'glx[h]', 'glx[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

model = addReaction(model, 'GOU', ...
    'metaboliteList', {'glx[h]', 'ser_L[h]', 'co2[h]'}, ...
    'stoichCoeffList', [-2, 1, 1], 'reversible', false);

model = addReaction(model, 'T_SER', ...
    'metaboliteList', {'ser_L[h]', 'ser_L[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);


% STARCH SYNTHESIS

model = addReaction(model, 'PGIAh', ...
    'metaboliteList', {'f6p_B[h]', 'g6p_A[h]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

model = addReaction(model, 'PGMTh', ...
    'metaboliteList', {'g6p_A[h]', 'g1p[h]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

model = addReaction(model, 'GLPTHi', ...
    'metaboliteList', {'g1p[h]', 'adpglc[h]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

model = addReaction(model, 'Biomass_starch', ...
    'metaboliteList', {'adpglc[h]'}, ...
    'stoichCoeffList', [-1], 'reversible', false);


% SUCROSE SYNTHESIS (cytosolic)

model = addReaction(model, 'FBAc', ...
    'metaboliteList', {'dhap[c]', 'dhap[c]', 'fdp_B[c]'}, ...
    'stoichCoeffList', [-1, -1, 1], 'reversible', false);

model = addReaction(model, 'FPPc', ...
    'metaboliteList', {'fdp_B[c]', 'f6p_B[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

model = addReaction(model, 'PGIc', ...
    'metaboliteList', {'f6p_B[c]', 'g6p_A[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

model = addReaction(model, 'PGMTc', ...
    'metaboliteList', {'g6p_A[c]', 'g1p[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

model = addReaction(model, 'UG1PUT', ...
    'metaboliteList', {'g1p[c]', 'udpg[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

model = addReaction(model, 'UFAGT', ...
    'metaboliteList', {'f6p_B[c]', 'udpg[c]'}, ...
    'stoichCoeffList', [-1, -1], 'reversible', false);


% CYTOSOLIC GLYCOLYSIS / ANAPLEROTIC

model = addReaction(model, 'FGAM_c', ...
    'metaboliteList', {'3pg[c]', 'pep[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

model = addReaction(model, 'PYK', ...
    'metaboliteList', {'pep[c]', 'pyr[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

model = addReaction(model, 'PPC', ...
    'metaboliteList', {'pep[c]', 'co2[c]', 'oaa[c]'}, ...
    'stoichCoeffList', [-1, -1, 1], 'reversible', false);

model = addReaction(model, 'ALT', ...
    'metaboliteList', {'pyr[c]', 'ala_L[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

model = addReaction(model, 'MDHc', ...
    'metaboliteList', {'mal_L[c]', 'oaa[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

model = addReaction(model, 'ASPTc', ...
    'metaboliteList', {'oaa[c]', 'asp_L[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

model = addReaction(model, 'GLUDHc', ...
    'metaboliteList', {'akg[c]', 'glu_L[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

model = addReaction(model, 'EX_glu_L_c', ...
    'metaboliteList', {'glu_L[c]'}, ...
    'stoichCoeffList', [-1], 'reversible', false);

model = addReaction(model, 'EX_asp_L_c', ...
    'metaboliteList', {'asp_L[c]'}, ...
    'stoichCoeffList', [-1], 'reversible', false);

% TRANSPORTERS  

model = addReaction(model, 'T_T3P', ...
    'metaboliteList', {'3pg[h]', '3pg[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

model = addReaction(model, 'T_TP', ...
    'metaboliteList', {'dhap[h]', 'dhap[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

model = addReaction(model, 'T_PEP', ...
    'metaboliteList', {'pep[h]', 'pep[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

model = addReaction(model, 'CO2t', ...
    'metaboliteList', {'co2[e]', 'co2[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

model = addReaction(model, 'CO2th', ...
    'metaboliteList', {'co2[c]', 'co2[h]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

% PLASTIDIC GLYCOLYSIS (chloroplast)

model = addReaction(model, 'ENO_h', ...
    'metaboliteList', {'3pg[h]', 'pep[h]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

model = addReaction(model, 'PYK_h', ...
    'metaboliteList', {'pep[h]', 'pyr[h]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

model = addReaction(model, 'EX_pyr', ...
    'metaboliteList', {'pyr[h]'}, ...
    'stoichCoeffList', [-1], 'reversible', false);

model = addReaction(model, 'EX_shikimate', ...
    'metaboliteList', {'pep[h]'}, ...
    'stoichCoeffList', [-1], 'reversible', false);


% EXCHANGE / BOUNDARY REACTIONS

model = addReaction(model, 'EX_co2_e', ...
    'metaboliteList', {'co2[e]'}, ...
    'stoichCoeffList', [1], 'reversible', false);

model = addReaction(model, 'EX_ala_L_c', ...
    'metaboliteList', {'ala_L[c]'}, ...
    'stoichCoeffList', [-1], 'reversible', false);

model = addReaction(model, 'EX_glx_c', ...
    'metaboliteList', {'glx[c]'}, ...
    'stoichCoeffList', [-1], 'reversible', false);

model = addReaction(model, 'EX_ser_c', ...
    'metaboliteList', {'ser_L[c]'}, ...
    'stoichCoeffList', [-1], 'reversible', false);

% MITOCHONDRIAL TCA CYCLE + GLYOXYLATE SHUNT + ANAPLEROTIC + TRANSPORTERS

model = addReaction(model, 'PDHm', ...
    'metaboliteList', {'pyr[m]', 'aca[m]', 'co2[m]'}, ...
    'stoichCoeffList', [-1, 1, 1], 'reversible', false);

model = addReaction(model, 'CSm', ...
    'metaboliteList', {'oaa[m]', 'aca[m]', 'cit[m]'}, ...
    'stoichCoeffList', [-1, -1, 1], 'reversible', false);

model = addReaction(model, 'ACONTm', ...
    'metaboliteList', {'cit[m]', 'icit[m]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

model = addReaction(model, 'ICDHm', ...
    'metaboliteList', {'icit[m]', 'akg[m]', 'co2[m]'}, ...
    'stoichCoeffList', [-1, 1, 1], 'reversible', false);

model = addReaction(model, 'AKGDHm', ...
    'metaboliteList', {'akg[m]', 'sca[m]', 'co2[m]'}, ...
    'stoichCoeffList', [-1, 1, 1], 'reversible', false);

model = addReaction(model, 'SUCOASm', ...
    'metaboliteList', {'sca[m]', 'succ[m]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

model = addReaction(model, 'SUCDm', ...
    'metaboliteList', {'succ[m]', 'fum[m]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

model = addReaction(model, 'FUMm', ...
    'metaboliteList', {'fum[m]', 'mal_L[m]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

model = addReaction(model, 'MDHm', ...
    'metaboliteList', {'mal_L[m]', 'oaa[m]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

model = addReaction(model, 'ASPTAm', ...
    'metaboliteList', {'akg[m]', 'asp_L[m]', 'glu_L[m]', 'oaa[m]'}, ...
    'stoichCoeffList', [-1, -1, 1, 1], 'reversible', false);

model = addReaction(model, 'AATm', ...
    'metaboliteList', {'ala_L[m]', 'akg[m]', 'pyr[m]', 'glu_L[m]'}, ...
    'stoichCoeffList', [-1, -1, 1, 1], 'reversible', true);

model = addReaction(model, 'ICLm', ...
    'metaboliteList', {'icit[m]', 'glx[m]', 'succ[m]'}, ...
    'stoichCoeffList', [-1, 1, 1], 'reversible', false);

model = addReaction(model, 'MALSm', ...
    'metaboliteList', {'aca[m]', 'glx[m]', 'mal_L[m]'}, ...
    'stoichCoeffList', [-1, -1, 1], 'reversible', false);

model = addReaction(model, 'MEm', ...
    'metaboliteList', {'mal_L[m]', 'pyr[m]', 'co2[m]'}, ...
    'stoichCoeffList', [-1, 1, 1], 'reversible', false);

model = addReaction(model, 'PYKm', ...
    'metaboliteList', {'pep[m]', 'pyr[m]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

model = addReaction(model, 'PYRtm', ...
    'metaboliteList', {'pyr[c]', 'pyr[m]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

model = addReaction(model, 'MALtm', ...
    'metaboliteList', {'mal_L[c]', 'mal_L[m]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

model = addReaction(model, 'OAAtm', ...
    'metaboliteList', {'oaa[c]', 'oaa[m]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

model = addReaction(model, 'ASPtm', ...
    'metaboliteList', {'asp_L[c]', 'asp_L[m]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

model = addReaction(model, 'GLUtm', ...
    'metaboliteList', {'glu_L[c]', 'glu_L[m]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

model = addReaction(model, 'ALAtm', ...
    'metaboliteList', {'ala_L[c]', 'ala_L[m]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

model = addReaction(model, 'PEPtm', ...
    'metaboliteList', {'pep[c]', 'pep[m]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

model = addReaction(model, 'CO2tm', ...
    'metaboliteList', {'co2[m]', 'co2[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

model = addReaction(model, 'AKGtm', ...
    'metaboliteList', {'akg[m]', 'akg[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

% BOUNDS

rev_idx = model.lb < 0;
irr_idx = model.lb >= 0;

model.lb(irr_idx) = 0;
model.ub(irr_idx) = 1;
model.lb(rev_idx) = -1;
model.ub(rev_idx) = 1;

model.ub(13) = 0.00003;  
model.ub(23) = 0.00001; 
model.ub(29) = 0.002; 
model.ub(51) = 0.002; 

% FVA

modelIrrev = convertToIrreversible(model);

[mini, maxi] = fluxVariability(modelIrrev, 0);
view_table = table(modelIrrev.rxns, mini, maxi);

% Flux sampling
options.nStepsPerPoint = 1000;
options.nPointsReturned = 8000;
options.nWarmupPoints = 1000;

[samples, s] = sampleCbModel(modelIrrev, '', 'ACHR', options);

writeSBML(model, 'photosynthesis_model_out.xml');

T = table(modelIrrev.rxns, mini, maxi, s);
writetable(T,'fluxes_fva.csv','Delimiter',',')
