% Photosynthesis / Carbon Metabolism Model
% Based on iCre1355 (opt_model.xml) naming conventions
% Compartments: [h] = chloroplast/plastid (.p), [c] = cytosol (.c),
%               [m] = mitochondria, [e] = extracellular/atmosphere
%
% EDIT: TCA cycle reactions (CS, ACONT, ICDH, MALS, MDH) are now present
%       ONLY in the mitochondrial compartment.  The cytosolic block retains
%       only genuinely cytosolic reactions: glycolysis/anaplerotic steps
%       (FGAM_c / ENO, PYK, PPC) and amino-acid interconversions.
%       PDHc has been REMOVED; pyruvate dehydrogenase runs only as PDHm.
%       Cytosolic acetyl-CoA (aca[c]) and the cytosolic citrate/isocitrate
%       branch (CS, ACONT, ICDHc, MALSc, MDHc) are eliminated.
%       The malate-aspartate shuttle transporters (MALtm, OAAtm, ASPtm,
%       GLUtm, ALAtm, PEPtm, PYRtm, CO2tm) remain to link cytosol and
%       mitochondria.

% mod = readSBML('iCre1355_auto.xml', 1000);

model = createModel;

% -------------------------------------------------------------------------
% CALVIN CYCLE
% -------------------------------------------------------------------------
% RUBISCO_CO2  : RuBP + CO2 -> 2x 3-PGA
model = addReaction(model, 'RBPCh', ...
    'metaboliteList', {'rb15bp[h]', 'co2[h]', '3pg[h]'}, ...
    'stoichCoeffList', [-1, -1, 2], 'reversible', false);

% GAPDH.p      : 3PGA -> DHAP
model = addReaction(model, 'GAPDH_nadp_hi', ...
    'metaboliteList', {'3pg[h]', 'dhap[h]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

% ALD          : DHAP + E4P -> SBP
model = addReaction(model, 'ALDh', ...
    'metaboliteList', {'dhap[h]', 'e4p[h]', 's17bp[h]'}, ...
    'stoichCoeffList', [-1, -1, 1], 'reversible', true);

% SBPase       : SBP -> S7P
model = addReaction(model, 'SBPase', ...
    'metaboliteList', {'s17bp[h]', 's7p[h]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

% FBA.p        : 2x DHAP -> FBP
model = addReaction(model, 'FBAh', ...
    'metaboliteList', {'dhap[h]', 'dhap[h]', 'fdp_B[h]'}, ...
    'stoichCoeffList', [-1, -1, 1], 'reversible', true);

% FBPase       : FBP -> F6P
model = addReaction(model, 'BFBPh', ...
    'metaboliteList', {'fdp_B[h]', 'f6p_B[h]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

% TK1          : DHAP + S7P -> Xu5P + R5P
model = addReaction(model, 'TKT1h', ...
    'metaboliteList', {'dhap[h]', 's7p[h]', 'xu5p_D[h]', 'r5p[h]'}, ...
    'stoichCoeffList', [-1, -1, 1, 1], 'reversible', true);

% TK2          : DHAP + F6P -> Xu5P + E4P
model = addReaction(model, 'TKT2h', ...
    'metaboliteList', {'dhap[h]', 'f6p_B[h]', 'xu5p_D[h]', 'e4p[h]'}, ...
    'stoichCoeffList', [-1, -1, 1, 1], 'reversible', true);

% TA (TK3)     : E4P + F6P -> DHAP + S7P
model = addReaction(model, 'TAh', ...
    'metaboliteList', {'e4p[h]', 'f6p_B[h]', 'dhap[h]', 's7p[h]'}, ...
    'stoichCoeffList', [-1, -1, 1, 1], 'reversible', true);

% RPE          : Xu5P -> Ru5P
model = addReaction(model, 'RPEh', ...
    'metaboliteList', {'xu5p_D[h]', 'ru5p_D[h]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

% RPI          : R5P -> Ru5P
model = addReaction(model, 'RPIh', ...
    'metaboliteList', {'r5p[h]', 'ru5p_D[h]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

% PRK          : Ru5P -> RuBP
model = addReaction(model, 'PRUK', ...
    'metaboliteList', {'ru5p_D[h]', 'rb15bp[h]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

% -------------------------------------------------------------------------
% PHOTORESPIRATION
% -------------------------------------------------------------------------
% RUBISCO_O2   : RuBP -> 3PGA + 2-phosphoglycolate
model = addReaction(model, 'RBCh', ...
    'metaboliteList', {'rb15bp[h]', '3pg[h]', '2pglyc[h]'}, ...
    'stoichCoeffList', [-1, 1, 1], 'reversible', false);

% PGP          : 2-phosphoglycolate -> glycolate
model = addReaction(model, 'PGP', ...
    'metaboliteList', {'2pglyc[h]', 'glyclt[h]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

% GCLDH        : glycolate -> glyoxylate (chloroplast)
model = addReaction(model, 'GCLDH', ...
    'metaboliteList', {'glyclt[h]', 'glx[h]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

% T_glx        : glyoxylate chloroplast -> cytosol
model = addReaction(model, 'T_glx', ...
    'metaboliteList', {'glx[h]', 'glx[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

% GOU          : 2x glyoxylate -> serine + CO2
model = addReaction(model, 'GOU', ...
    'metaboliteList', {'glx[h]', 'ser_L[h]', 'co2[h]'}, ...
    'stoichCoeffList', [-2, 1, 1], 'reversible', false);

% T_SER        : serine chloroplast -> cytosol
model = addReaction(model, 'T_SER', ...
    'metaboliteList', {'ser_L[h]', 'ser_L[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

% SGA1_GK      : serine -> 3PGA (chloroplast)
%model = addReaction(model, 'SGA1_GK', ...
%    'metaboliteList', {'ser_L[h]', 'glyc_R[h]'}, ...
%   'stoichCoeffList', [-1, 1], 'reversible', false);

% SGA1_GK      : serine -> 3PGA (chloroplast)
%model = addReaction(model, 'SGA2_GK', ...
%    'metaboliteList', {'glyc_R[h]', '3pg[h]'}, ...
%    'stoichCoeffList', [-1, 1], 'reversible', true);
% -------------------------------------------------------------------------
% STARCH SYNTHESIS
% -------------------------------------------------------------------------
% PGI.p        : F6P -> G6P (chloroplast)
model = addReaction(model, 'PGIAh', ...
    'metaboliteList', {'f6p_B[h]', 'g6p_A[h]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

% PGM.p        : G6P -> G1P (chloroplast)
model = addReaction(model, 'PGMTh', ...
    'metaboliteList', {'g6p_A[h]', 'g1p[h]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

% AGP          : G1P -> ADP-glucose
model = addReaction(model, 'GLPTHi', ...
    'metaboliteList', {'g1p[h]', 'adpglc[h]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

% SS           : ADP-glucose -> Starch
model = addReaction(model, 'Biomass_starch', ...
    'metaboliteList', {'adpglc[h]'}, ...
    'stoichCoeffList', [-1], 'reversible', false);

% -------------------------------------------------------------------------
% SUCROSE SYNTHESIS (cytosolic)
% -------------------------------------------------------------------------
% FBA.c        : 2x DHAP -> FBP (cytosol)
model = addReaction(model, 'FBAc', ...
    'metaboliteList', {'dhap[c]', 'dhap[c]', 'fdp_B[c]'}, ...
    'stoichCoeffList', [-1, -1, 1], 'reversible', false);

% FPP.c        : FBP -> F6P (cytosol)
model = addReaction(model, 'FPPc', ...
    'metaboliteList', {'fdp_B[c]', 'f6p_B[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

% PGI.c        : F6P -> G6P (cytosol)
model = addReaction(model, 'PGIc', ...
    'metaboliteList', {'f6p_B[c]', 'g6p_A[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

% PGM.c        : G6P -> G1P (cytosol)
model = addReaction(model, 'PGMTc', ...
    'metaboliteList', {'g6p_A[c]', 'g1p[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

% GPU          : G1P -> UDP-glucose (cytosol)
model = addReaction(model, 'UG1PUT', ...
    'metaboliteList', {'g1p[c]', 'udpg[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

% SPS          : F6P + UDP-glucose -> sucrose-6P (cytosol)
model = addReaction(model, 'UFAGT', ...
    'metaboliteList', {'f6p_B[c]', 'udpg[c]'}, ...
    'stoichCoeffList', [-1, -1], 'reversible', false);

% -------------------------------------------------------------------------
% CYTOSOLIC GLYCOLYSIS / ANAPLEROTIC
% (TCA cycle reactions CS, ACONT, ICDH, MALS, MDH removed from cytosol)
% -------------------------------------------------------------------------
% ENO / FGAM_c : 3PGA -> PEP (cytosol)
model = addReaction(model, 'FGAM_c', ...
    'metaboliteList', {'3pg[c]', 'pep[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

% PYK          : PEP -> pyruvate (cytosol)
%                Pyruvate is then exported to mitochondria via PYRtm
model = addReaction(model, 'PYK', ...
    'metaboliteList', {'pep[c]', 'pyr[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

% REMOVED: PDHc  (pyruvate dehydrogenase runs only as PDHm in mitochondria)
% REMOVED: CS    (citrate synthase runs only as CSm in mitochondria)
% REMOVED: ACONT (aconitase runs only as ACONTm in mitochondria)
% REMOVED: ICDHc (isocitrate dehydrogenase runs only as ICDHm in mitochondria)
% REMOVED: MALSc (malate synthase runs only as MALSm in mitochondria)
% REMOVED: MDHc  (malate dehydrogenase runs only as MDHm in mitochondria)

% PPC (anaplerotic): PEP + CO2 -> OAA (cytosol)
%   OAA is exported to mitochondria via OAAtm for entry into the TCA cycle
model = addReaction(model, 'PPC', ...
    'metaboliteList', {'pep[c]', 'co2[c]', 'oaa[c]'}, ...
    'stoichCoeffList', [-1, -1, 1], 'reversible', false);

% -------------------------------------------------------------------------
% AMINO ACIDS (cytosolic interconversions; de-novo synthesis feeds from
%              mitochondrial TCA intermediates via transporters)
% -------------------------------------------------------------------------
% ALT          : pyruvate <-> alanine (cytosol)
model = addReaction(model, 'ALT', ...
    'metaboliteList', {'pyr[c]', 'ala_L[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

% MDHm  : malate <-> OAA  (near eq -> oaa retrievable)
model = addReaction(model, 'MDHc', ...
    'metaboliteList', {'mal_L[c]', 'oaa[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

% ASPTc        : OAA <-> aspartate (cytosol)
%                OAA pool sourced via OAAtm from mitochondrial TCA
model = addReaction(model, 'ASPTc', ...
    'metaboliteList', {'oaa[c]', 'asp_L[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

% GLUDHc       : 2-oxoglutarate <-> glutamate (cytosol)
%                2-OG pool sourced via mitochondrial ICDH + export
model = addReaction(model, 'GLUDHc', ...
    'metaboliteList', {'akg[c]', 'glu_L[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

% Exchange sinks
model = addReaction(model, 'EX_glu_L_c', ...
    'metaboliteList', {'glu_L[c]'}, ...
    'stoichCoeffList', [-1], 'reversible', false);

model = addReaction(model, 'EX_asp_L_c', ...
    'metaboliteList', {'asp_L[c]'}, ...
    'stoichCoeffList', [-1], 'reversible', false);

% -------------------------------------------------------------------------
% TRANSPORTERS  (chloroplast <-> cytosol)
% -------------------------------------------------------------------------
% T_3PGA       : 3PGA chloroplast <-> cytosol
model = addReaction(model, 'T_T3P', ...
    'metaboliteList', {'3pg[h]', '3pg[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

% T_TP         : DHAP chloroplast <-> cytosol
model = addReaction(model, 'T_TP', ...
    'metaboliteList', {'dhap[h]', 'dhap[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

% T_PEP        : PEP chloroplast <-> cytosol
model = addReaction(model, 'T_PEP', ...
    'metaboliteList', {'pep[h]', 'pep[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

% CO2t         : CO2 extracellular -> free CO2
model = addReaction(model, 'CO2t', ...
    'metaboliteList', {'co2[e]', 'co2[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

% CO2th        : CO2 cytosol <-> chloroplast
model = addReaction(model, 'CO2th', ...
    'metaboliteList', {'co2[c]', 'co2[h]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

% -------------------------------------------------------------------------
% PLASTIDIC GLYCOLYSIS (chloroplast)
% -------------------------------------------------------------------------
% ENO_h        : 3PGA -> PEP (chloroplast)
model = addReaction(model, 'ENO_h', ...
    'metaboliteList', {'3pg[h]', 'pep[h]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

% PYK_h        : PEP -> pyruvate (chloroplast, feeds fatty-acid synthesis)
model = addReaction(model, 'PYK_h', ...
    'metaboliteList', {'pep[h]', 'pyr[h]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

model = addReaction(model, 'EX_pyr', ...
    'metaboliteList', {'pyr[h]'}, ...
    'stoichCoeffList', [-1], 'reversible', false);

% Shikimate pathway sink (chloroplast PEP)
model = addReaction(model, 'EX_shikimate', ...
    'metaboliteList', {'pep[h]'}, ...
    'stoichCoeffList', [-1], 'reversible', false);

% -------------------------------------------------------------------------
% EXCHANGE / BOUNDARY REACTIONS
% -------------------------------------------------------------------------
model = addReaction(model, 'EX_co2_e', ...
    'metaboliteList', {'co2[e]'}, ...
    'stoichCoeffList', [1], 'reversible', false);

model = addReaction(model, 'EX_ala_L_c', ...
    'metaboliteList', {'ala_L[c]'}, ...
    'stoichCoeffList', [-1], 'reversible', false);

model = addReaction(model, 'EX_glx_c', ...
    'metaboliteList', {'glx[c]'}, ...
    'stoichCoeffList', [-1], 'reversible', false);

model = addReaction(model, 'EX_ser_c', ...
    'metaboliteList', {'ser_L[c]'}, ...
    'stoichCoeffList', [-1], 'reversible', false);

% =========================================================================
% MITOCHONDRIAL TCA CYCLE + GLYOXYLATE SHUNT + ANAPLEROTIC + TRANSPORTERS
% =========================================================================
% All TCA cycle carbon-processing reactions are exclusively mitochondrial.
%
% Retrievable-via-Keq pools (near-equilibrium reactions to measured anchors):
%   oaa     <- MDHm (mal_L) + ASPTAm (akg, asp_L <-> glu_L, oaa)
%   fum     <- FUMm (mal_L)
%   succoa  <- SUCOASm (succ)
%
% Free / clamped pools (irreversible steps; not pinned by measured neighbour):
%   cit, icit, pyr, pep, aca, glx

% ---- PDH: the sole entry point for pyruvate -> acetyl (mitochondrial) ----
% PDHm  : pyr(abc) -> aca(bc) + CO2(a)
model = addReaction(model, 'PDHm', ...
    'metaboliteList', {'pyr[m]', 'aca[m]', 'co2[m]'}, ...
    'stoichCoeffList', [-1, 1, 1], 'reversible', false);

% ---- TCA cycle (mitochondrial) ----
% CSm   : oaa + aca -> citrate
model = addReaction(model, 'CSm', ...
    'metaboliteList', {'oaa[m]', 'aca[m]', 'cit[m]'}, ...
    'stoichCoeffList', [-1, -1, 1], 'reversible', false);

% ACONTm: citrate <-> isocitrate
model = addReaction(model, 'ACONTm', ...
    'metaboliteList', {'cit[m]', 'icit[m]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

% ICDHm : isocitrate -> 2-oxoglutarate + CO2
model = addReaction(model, 'ICDHm', ...
    'metaboliteList', {'icit[m]', 'akg[m]', 'co2[m]'}, ...
    'stoichCoeffList', [-1, 1, 1], 'reversible', false);

% AKGDHm: 2-oxoglutarate -> succinyl-CoA + CO2
model = addReaction(model, 'AKGDHm', ...
    'metaboliteList', {'akg[m]', 'sca[m]', 'co2[m]'}, ...
    'stoichCoeffList', [-1, 1, 1], 'reversible', false);

% SUCOASm: succinyl-CoA <-> succinate  (near eq -> succoa retrievable)
model = addReaction(model, 'SUCOASm', ...
    'metaboliteList', {'sca[m]', 'succ[m]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

% SUCDm : succinate <-> fumarate  (near eq)
model = addReaction(model, 'SUCDm', ...
    'metaboliteList', {'succ[m]', 'fum[m]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

% FUMm  : fumarate <-> malate  (near eq -> fum retrievable)
model = addReaction(model, 'FUMm', ...
    'metaboliteList', {'fum[m]', 'mal_L[m]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

% MDHm  : malate <-> OAA  (near eq -> oaa retrievable)
model = addReaction(model, 'MDHm', ...
    'metaboliteList', {'mal_L[m]', 'oaa[m]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

% ---- Aminotransferase bridges to measured amino-acid pools ----
% ASPTAm: akg + asp_L <-> glu_L + oaa  (double anchor for oaa)
model = addReaction(model, 'ASPTAm', ...
    'metaboliteList', {'akg[m]', 'asp_L[m]', 'glu_L[m]', 'oaa[m]'}, ...
    'stoichCoeffList', [-1, -1, 1, 1], 'reversible', false);

% AATm  : ala_L + akg <-> pyr + glu_L  (near eq)
model = addReaction(model, 'AATm', ...
    'metaboliteList', {'ala_L[m]', 'akg[m]', 'pyr[m]', 'glu_L[m]'}, ...
    'stoichCoeffList', [-1, -1, 1, 1], 'reversible', true);

% ---- Glyoxylate shunt (mitochondrial) ----
% ICLm  : isocitrate -> glyoxylate + succinate
model = addReaction(model, 'ICLm', ...
    'metaboliteList', {'icit[m]', 'glx[m]', 'succ[m]'}, ...
    'stoichCoeffList', [-1, 1, 1], 'reversible', false);

% MALSm : acetyl + glyoxylate -> malate
model = addReaction(model, 'MALSm', ...
    'metaboliteList', {'aca[m]', 'glx[m]', 'mal_L[m]'}, ...
    'stoichCoeffList', [-1, -1, 1], 'reversible', false);

% ---- Anaplerotic / cataplerotic (mitochondrial) ----
% MEm   : malate -> pyruvate + CO2  (malic enzyme)
model = addReaction(model, 'MEm', ...
    'metaboliteList', {'mal_L[m]', 'pyr[m]', 'co2[m]'}, ...
    'stoichCoeffList', [-1, 1, 1], 'reversible', false);

% PYKm  : PEP -> pyruvate (mitochondrial pyruvate kinase)
model = addReaction(model, 'PYKm', ...
    'metaboliteList', {'pep[m]', 'pyr[m]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', false);

% ---- Mitochondria <-> cytosol transporters ----
model = addReaction(model, 'PYRtm', ...
    'metaboliteList', {'pyr[c]', 'pyr[m]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

model = addReaction(model, 'MALtm', ...
    'metaboliteList', {'mal_L[c]', 'mal_L[m]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

model = addReaction(model, 'OAAtm', ...
    'metaboliteList', {'oaa[c]', 'oaa[m]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

model = addReaction(model, 'ASPtm', ...
    'metaboliteList', {'asp_L[c]', 'asp_L[m]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

model = addReaction(model, 'GLUtm', ...
    'metaboliteList', {'glu_L[c]', 'glu_L[m]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

model = addReaction(model, 'ALAtm', ...
    'metaboliteList', {'ala_L[c]', 'ala_L[m]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

model = addReaction(model, 'PEPtm', ...
    'metaboliteList', {'pep[c]', 'pep[m]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

model = addReaction(model, 'CO2tm', ...
    'metaboliteList', {'co2[m]', 'co2[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

% Add transporter for 2-oxoglutarate (akg): mitochondrial TCA -> cytosol
% for cytosolic GLUDHc and ASPTc; not present in original but required
% now that cytosolic aca/TCA route is removed.
model = addReaction(model, 'AKGtm', ...
    'metaboliteList', {'akg[m]', 'akg[c]'}, ...
    'stoichCoeffList', [-1, 1], 'reversible', true);

% -------------------------------------------------------------------------
% BOUNDS
% -------------------------------------------------------------------------
rev_idx = model.lb < 0;
irr_idx = model.lb >= 0;

model.lb(irr_idx) = 0;
model.ub(irr_idx) = 1;
model.lb(rev_idx) = -1;
model.ub(rev_idx) = 1;

model.ub(13) = 0.00003;   % RBCh (oxygenase cap, unchanged)
model.ub(23) = 0.00001; 
model.ub(29) = 0.002; 
model.ub(51) = 0.002; 


% -------------------------------------------------------------------------
% FLUX VARIABILITY ANALYSIS
% -------------------------------------------------------------------------
% [mini, maxi] = fluxVariability(model, 0);
% view_table = table(model.rxns, mini, maxi);

modelIrrev = convertToIrreversible(model);

[mini, maxi] = fluxVariability(modelIrrev, 0);
view_table = table(modelIrrev.rxns, mini, maxi);

% Now sample the irreversible model
%options.nStepsPerPoint = 1000;
%options.nPointsReturned = 8000;
%options.nWarmupPoints = 1000;

%[samples, s] = sampleCbModel(modelIrrev, '', 'ACHR', options);

% writeSBML(model, 'photosynthesis_model_out.xml');
%% 